swagger: '2.0'

info:
  version: "0.0.1"
  title: SMP Native REST API
  contact:
      email: "adam@stylemepretty.com"

host: 10.98.192.9
produces:
  - application/json

tags:
    -
      name: gallery
      description: Api routes involving a single gallery or collection of galleries
    -
      name: image
      description: Api routes involving a single image or collection of images
    -
      name: user
      description: Api routes involving user actions
    -
      name: vendor
      description: Api routes involving vendor actions

paths:
  /wp-json/jwt-auth/v1/token:
    post:
      tags:
          - user
      summary: Request access token
      operationId: getToken
      schemes:
        - http
        - https
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        -
          name: username
          in: formData
          required: true
          type: string
        -
          name: password
          in: formData
          required: true
          type: string
      responses:
        200:
          description: Successful response
          schema:
             type: object
             properties:
              token:
                type: string
                description: Authorization token
              user_email:
                type: string
              user_nicename:
                type: string
              user_display_name:
                type: string
        403:
          description: Unauthorized request
          schema:
             $ref: '#/definitions/Error'

  /wp-json/jwt-auth/v1/token/validate:
    post:
      tags:
          - user
      summary: Validates a access token
      operationId: validateToken
      schemes:
        - http
        - https
      parameters:
        -
          name: Authorization
          in: header
          description: Authorization token
          required: true
          type: string
      responses:
        200:
          description: Successful response
          schema:
             type: object
             properties:
              code:
                type: string
                description: If valid code will be set to jwt_auth_valid_token
        403:
          description: Unauthorized request
          schema:
             $ref: '#/definitions/Error'
        500:
          description: Failed response
          schema:
             $ref: '#/definitions/Error'

  /wp-json/wp/v2/users:
    post:
      tags:
          - user
      summary: Create a new user
      operationId: createUser
      schemes:
        - http
        - https
      parameters:
        -
          name: username
          in: formData
          required: true
          type: string
        -
          name: email
          in: formData
          required: true
          type: string
        -
          name: password
          in: formData
          required: true
          type: string
      responses:
        200:
          description: Successful response
          schema:
             $ref: '#/definitions/User'
        403:
          description: Failed response
          schema:
             $ref: '#/definitions/Error'
        500:
          description: Failed response
          schema:
             $ref: '#/definitions/Error'

  /api/v2/user:
    get:
      tags:
          - user
      summary: Get additional details about the current user
      parameters:
        -
          name: Authorization
          in: header
          description: Authorization token
          required: true
          type: string
      responses:
        200:
          description: Successful response
          schema:
             $ref: '#/definitions/User'
        403:
          description: Unauthorized response
          schema:
             $ref: '#/definitions/Error'
        500:
          description: Failed response
          schema:
             $ref: '#/definitions/Error'
    put:
      tags:
          - user
      summary: Save additional details about the current user
      parameters:
        -
          name: Authorization
          in: header
          description: Authorization token
          required: true
          type: string
      responses:
        200:
          description: Successful response
          schema:
             $ref: '#/definitions/User'
        403:
          description: Invalid token
          schema:
             $ref: '#/definitions/Error'
        500:
          description: Failed response
          schema:
             $ref: '#/definitions/Error'

  /api/v2/user/follow:
    get:
      tags:
        - user
      parameters:
        -
          name: Authorization
          in: header
          description: Authorization token
          required: true
          type: string
      summary: Returns all `Followable` objects the current user is following
      responses:
        200:
          description: Successful response
          schema:
             $ref: '#/definitions/Following'
        403:
          description: Unauthorized response
          schema:
             $ref: '#/definitions/Error'
        500:
          description: Failed response
          schema:
             $ref: '#/definitions/Error'
    post:
      tags:
        - user
      parameters:
        -
          name: Authorization
          in: header
          description: Authorization token
          required: true
          type: string
        -
          name: taxonomy
          in: query
          description: type of object to follow, can be "detail" or "vendor"
          required: true
          type: string
        -
          name: id
          in: query
          description: Id of `Detail` object or `Vendor` object
          required: true
          type: integer
      summary: Allow users to follow a `Object` which can be either a detail or vendor
      responses:
        200:
          description: Successful response
          schema:
             $ref: '#/definitions/Following'
        403:
          description: Unauthorized response
          schema:
             $ref: '#/definitions/Error'
        500:
          description: Failed response
          schema:
             $ref: '#/definitions/Error'
    delete:
      tags:
        - user
      parameters:
        -
          name: Authorization
          in: header
          description: Authorization token
          required: true
          type: string
        -
          name: taxonomy
          in: query
          description: type of object to unfollowing, can be "detail" or "vendor"
          required: true
          type: string
        -
          name: id
          in: query
          description: Id of `Detail` object or `Vendor` object
          required: true
          type: integer
      summary: Unfollow a `Object`
      responses:
        200:
          description: Successful response
          schema:
             $ref: '#/definitions/Following'
        403:
          description: Unauthorized response
          schema:
             $ref: '#/definitions/Error'
        500:
          description: Failed response
          schema:
             $ref: '#/definitions/Error'

  /api/v2/user/follows/recommended:
    get:
      tags:
          - user
      summary: Get an ordered list of follows to recommend to the user
      parameters:
        -
          name: Authorization
          in: header
          description: Authorization token
          required: true
          type: string
      responses:
        200:
          description: Successful response
          schema:
             $ref: '#/definitions/Followable'
        403:
          description: Invalid token
          schema:
             $ref: '#/definitions/Error'

  /api/v2/user/favorite:
    get:
      tags:
          - user
      summary: Search users favorite images.
      parameters:
        -
          name: Authorization
          in: header
          description: Authorization token
          required: true
          type: string
        -
          name: query
          in: query
          description: Keyword entered by user for search
          required: true
          type: string
      responses:
        200:
          description: Successful response
          schema:
             $ref: '#/definitions/Images'
        403:
          description: Invalid token
          schema:
             $ref: '#/definitions/Error'
    post:
      tags:
          - user
      summary: Create a new favorite for the current user
      parameters:
        -
          name: Authorization
          in: header
          description: Authorization token
          required: true
          type: string
        -
          name: taxonomy
          in: query
          description: type of object to favorite, currenty only supporting a tag
          required: true
          type: string
        -
          name: id
          in: query
          description: Id of `Tag` to favorite
          required: true
          type: integer
      responses:
        200:
          description: Successful response
          schema:
             $ref: '#/definitions/Images'
        403:
          description: Invalid token
          schema:
             $ref: '#/definitions/Error'
    delete:
      tags:
          - user
      summary: Delete a favorite for the current user
      parameters:
        -
          name: Authorization
          in: header
          description: Authorization token
          required: true
          type: string
        -
          name: taxonomy
          in: query
          description: type of object to favorite, currenty only supporting a tag
          required: true
          type: string
        -
          name: id
          in: query
          description: Id of `Tag` to favorite
          required: true
          type: integer
      responses:
        200:
          description: Successful response
          schema:
             $ref: '#/definitions/Images'
        403:
          description: Invalid token
          schema:
             $ref: '#/definitions/Error'

  /api/v2/galleries:
    get:
      tags:
          - gallery
      summary: Get `GalleryPreview` objects matching queried `Vendor` and `Detail` parameters
      operationId: getFeedGalleries
      consumes:
        - application/json
      parameters:
        -
          name: perPage
          in: query
          description: Maximum number of `GalleryPreview` objects
          required: false
          type: integer
        -
          name: last
          in: query
          description: Query `GalleryPreview` objects with an id older than parameter
          required: false
          type: integer
        -
          name: vendor
          in: query
          description: Query `GalleryPreview` objects matching a `Vendor` id
          required: false
          type: integer
        -
          name: detail
          in: query
          description: Query `GalleryPreview` objects matching a `Detail` id
          required: false
          type: integer
      responses:
        200:
          description: Successful response
          schema:
             $ref: '#/definitions/Galleries'
        500:
          description: Failed response
          schema:
             $ref: '#/definitions/Error'

  /api/v2/gallery/{id}:
    get:
      tags:
        - gallery
      parameters:
        -
          name: id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: Successful response
          schema:
             $ref: '#/definitions/Gallery'
        500:
          description: Failed response
          schema:
             $ref: '#/definitions/Error'

  /api/v2/image/{id}:
    get:
      tags:
        - image
      summary: Get `Image` metdata
      operationId: getImageMetadata
      consumes:
        - application/json
      parameters:
        -
          name: id
          in: path
          description: Id of `Image` object to query
          required: true
          type: integer

      responses:
        200:
          description: Successful response
          schema:
             $ref: '#/definitions/Image'
        500:
          description: Failed response
          schema:
             $ref: '#/definitions/Error'

  /api/v2/vendor/{id}:
    get:
      tags:
        - vendor
      parameters:
        -
          name: id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: Successful response
          schema:
             $ref: '#/definitions/Vendor'
        500:
          description: Failed response
          schema:
             $ref: '#/definitions/Error'

  /api/v2/search/top:
    get:
      tags:
          - user
      summary: Get the most popular search results
      responses:
        200:
          description: Successful response
          schema:
             type: object
             properties:
              vendors:
                type: array
                items:
                  $ref: '#/definitions/Vendor'
              images:
                type: array
                items:
                  $ref: '#/definitions/Image'
              galleries:
                type: array
                items:
                  $ref: '#/definitions/Gallery'
        403:
          description: Invalid token
          schema:
             $ref: '#/definitions/Error'

  /api/v2/search/{type}:
    get:
      tags:
          - user
      summary: Get the most popular search results
      parameters:
        -
          name: type
          in: path
          description: Type of objects to search for (vendors, images, galleries)
          required: true
          type: string
          enum:
          - vendors
          - images
          - galleries
        -
          name: query
          in: query
          description: Search query
          required: true
          type: string
          enum:
          - vendors
          - images
          - galleries
        -
          name: perPage
          in: query
          description: Maximum number of objects
          required: false
          type: integer
        -
          name: last
          in: query
          description: Query objects with an id older than parameter
          required: false
          type: integer
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              last:
                type: integer
                description: The `Gallery` object ID matching request parameter or null
              perPage:
                type: integer
                description: Integer matching perPage request parameter or default value
              results:
                type: array
                description: Array of objects matching the type parameter.
                items:
                  type: object

definitions:
  Error:
    type: object
    properties:
      code:
        type: string
      message:
        type: string

  User:
    type: object
    properties:
      id:
        type: integer
      username:
        type: string
      email:
        type: string

  Following:
    type: array
    items:
      $ref: '#/definitions/Followable'

  Followable:
    type: object
    discriminator: taxonomy
    properties:
      name:
        type: string
        description: name to display
      id:
        type: integer
      taxonomy:
        type: string
        description: taxonomy of the 'Detail' or 'Vendor' for Vendor.
        enum:
        - season
        - style
        - setting
        - location
        - category
        - vendor
      following:
        type: boolean
        description: is the user following this?
    required:
    - id
    - name
    - taxonomy
    - following

  VendorPreview:
    description: Vendor associated with a Gallery
    allOf:
    - $ref: '#/definitions/Followable'
    - type: object
      properties:
        is_lbb:
          type: boolean
          description: Is the vendor an LBB member?

  Vendor:
    description: Vendor associated with a Gallery
    allOf:
    - $ref: '#/definitions/VendorPreview'
    - type: object
      properties:
        url:
          type: string
          description: URL of vendor website
        thumb:
          type: string
          description: profile image URL
        description:
          type: string
          description: description of the vendor

  ImagePreview:
    type: object
    properties:
      id:
        type: integer
      path:
        type: string
        description: Path to image source.
      width:
        type: integer
        description: Width of image.
      height:
        type: integer
        description: Height of image.

  Image:
    allOf:
    - $ref: '#/definitions/ImagePreview'
    - type: object
      properties:
        tags:
          type: array
          items:
            $ref: '#/definitions/Tag'
        vendors:
          type: array
          items:
            $ref: '#/definitions/VendorPreview'

  Images:
    type: array
    items:
      $ref: '#/definitions/ImagePreview'

  GalleryPreview:
    type: object
    properties:
      id:
        type: integer
      title:
        type: string
        description: title of gallery
      thumb:
        type: string
        description: Main image.
      thumbs:
        type: array
        items:
          type: string
          description: URL of thumbs

  Gallery:
    description: full gallery object
    allOf:
    - $ref: '#/definitions/GalleryPreview'
    - type: object
      properties:
        post_url:
          type: string
          description: URL of associated post.
        details:
          type: array
          items:
            $ref: '#/definitions/Detail'
        vendors:
          type: array
          items:
            $ref: '#/definitions/VendorPreview'
        images:
          type: array
          items:
            $ref: '#/definitions/ImagePreview'

  Galleries:
    type: object
    properties:
      total:
        type: integer
        description: Total `Gallery` objects matching query
      last:
        type: integer
        description: The `Gallery` object ID matching request parameter or null
      perPage:
        type: integer
        description: Integer matching perPage request parameter or default value
      results:
        type: array
        items:
          $ref: '#/definitions/GalleryPreview'

  Detail:
    description: Details for a gallery
    allOf:
    - $ref: '#/definitions/Followable'
    - type: object

  Tag:
    type: object
    description: Image level tag
    properties:
      id:
        type: integer
      name:
        type: string
        description: human readable tag name
