swagger: '2.0'

info:
  version: "0.0.1"
  title: SMP Native REST API

host: 10.98.192.9
produces:
  - application/json

paths:
  /api/native/galleries/feed:
    get:
      summary: Get feed galleries
      operationId: getFeedGalleries
      description: Gets `Gallery` objects.
      consumes:
        - application/json
      parameters:
        -
          name: Authorization
          in: header
          description: Authorization token
          required: false
          type: string
        -
          name: perPage
          in: query
          description: Maximum number of `Gallery` objects
          required: false
          type: integer
        -
          name: last
          in: query
          description: Query `Gallery` objects with an id older than parameter
          required: false
          type: integer
      responses:
        200:
          description: Successful response
          schema:
             $ref: '#/definitions/Galleries'
  /wp-json/jwt-auth/v1/token:
    post:
      summary: Request access token
      operationId: getToken
      description: Request access token.
      parameters:
        -
          name: username
          in: formData
          description: Authorization token
          required: true
          type: string
        -
          name: password
          in: formData
          required: false
          type: string
      responses:
        200:
          description: Successful response
          schema:
             type: object
             properties:
              token:
                type: string
                description: Authorization token
              user_email:
                type: string
              user_nicename:
                type: string
              user_display_name:
                type: string
        403:
          description: Failed login response
          schema:
             $ref: '#/definitions/Error'

definitions:
  Error:
    type: object
    properties:
      code:
        type: string
      message:
        type: string

  Galleries:
    type: object
    properties:
      total:
        type: integer
        description: Total `Gallery` objects matching query
      last:
        type: integer
        description: The `Gallery` object ID matching request parameter or null
      perPage:
        type: integer
        description: Integer matching perPage request parameter or default value
      results:
        type: array
        items:
          $ref: '#/definitions/Gallery'

  Gallery:
    type: object
    properties:
      id:
        type: integer
      title:
        type: string
        description: Description of product.
      thumb:
        type: string
        description: Main image.
      post_url:
        type: string
        description: Url of associated post.
      images:
        type: array
        items:
          $ref: '#/definitions/Image'

  Image:
    type: object
    properties:
      id:
        type: integer
      path:
        type: string
        description: Path to image source.
      width:
        type: integer
        description: Width of image.
      height:
        type: integer
        description: Height of image.
